" Author: Jack Browne
" Created: 12th November 2015

set nocompatible " Don't try to be vi compatible. This must be first

"Plugins {{{
set regexpengine=0
filetype off
source $HOME/.vim/plug.vim
filetype plugin indent on " Enable filetype detection
" }}}
" Colours {{{
"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif

"let base16colorspace=256

"set background=dark
colorscheme gruvbox " Use the same colorscheme as in the terminal

" }}}
" Whitespace {{{

set tabstop=2 " Number of spaces displayed by a TAB
set softtabstop=2 " Number of spaces in a TAB when editing
set expandtab " TABs are spaces
" }}}
" Folders {{{
" Centralize backups, swapfiles and undo history
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
if exists("&undodir")
	set undodir=~/.vim/undo
endif
" }}}
" UI tweaks {{{
set backspace=indent,eol,start " Allow backspace to work accross new lines and indentation

set number " Show line numbers

" Use relative line numbers
if exists("&relativenumber")
	set relativenumber
	au BufReadPost * set relativenumber
endif

set scrolloff=3 " Start scrolling three lines before the horizontal window border

set hidden " Allow hidden buffers, don't limit to 1 file per window

set laststatus=2

set noshowmode
"}}}
"Keybindings {{{
map j gj
map k gk

" Save a file as root (,W)
noremap <leader>W :w !sudo tee % > /dev/null<CR>
"}}}
" Airline {{{
let g:airline_powerline_fonts=1
let g:airline#extensions#syntastic#enabled=1
" }}}
" Syntastic {{{
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*
"
"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 0
" }}}
" LaTeX {{{
let g:tex_flavor='latex' " Always default to tex filetype
" }}}
set modelines=1
" vim:foldmethod=marker:foldlevel=0
